---
- name: get installed terraform version
  shell: "terraform version | sed -e 's/Terraform v//'"
  register: terraform_version_result
  ignore_errors: yes

- name: set terraform current version fact
  set_fact:
    terraform_current_version: "{{ terraform_version_result.stdout|default('') }}"
  register: terraform_fact_result

- name: get latest stable terraform tag
  uri:
    url: "{{ terraform_release_api_url }}"
  ignore_errors: yes
  register: terraform_github_result
  when: terraform_version == 'latest'

- name: set terraform latest version fact
  set_fact:
    terraform_version: "{{ terraform_github_result.json.tag_name|default(terraform_default_version)|replace('v','') }}"
  when: terraform_version == 'latest'

- name: set terraform version fact
  set_fact:
    terraform_version: "{{ terraform_default_version }}"
  when: terraform_version == '' or terraform_version is none
