---
# VirtualBox tools installation.
- name: Check if VirtualBox is running the guest VM.
  stat:
    path: "/home/{{ vagrant_user }}/.vbox_version"
  register: virtualbox_check

- include: virtualbox.yml
  when: virtualbox_check.stat.exists
