---
- name: add docker repository GPG key
  apt_key: keyserver="{{ docker_apt_keyserver }}" id="{{ docker_apt_key_id }}"
  when: ansible_lsb.id == 'Debian' or ansible_lsb.id == 'Ubuntu'

- name: add docker main repository
  apt_repository: repo="deb {{ docker_apt_url }} {{ ansible_lsb.id|lower }}-{{ ansible_lsb.codename|lower }} {{ docker_repo_branch|default('main') }}" state=present filename="docker_official"
  when: ansible_lsb.id == 'Debian' or ansible_lsb.id == 'Ubuntu'
  register: docker_apt_result

- name: ensure right permissions on apt sources list
  file:
    path: /etc/apt/sources.list.d/docker_official.list
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'

- name: apt update list for new docker repository
  apt: update_cache=yes
  when: docker_apt_result.changed

- name: install docker dependencies
  apt: name={{ item }} state=present
  with_items:
  - acl
  - cgroup-lite
  - apparmor

- name: install docker engine
  apt: name=docker-engine state={{ docker_state}}
