---
- include: debian_install_docker.yml
  when: ansible_os_family == 'Debian'
  tags:
  - docker

- include: install_docker_compose.yml
  tags:
  - docker
  - docker-compose

- include: install_docker_machine.yml
  tags:
  - docker
  - docker-machine

- include: config.yml
  tags:
  - docker
