---
- name: disable dnsmasq base in network manager
  lineinfile: >
    dest=/etc/NetworkManager/NetworkManager.conf
    regexp='^dns=dnsmasq'
    line='#dns=dnsmasq'
    owner=root
    group=root
    mode=0644
    backup=yes
  notify:
    - restart network manager

- name: install full dnsmasq
  apt: name=dnsmasq state=present

- name: configure dnsmasq
  template: >
    src=dnsmasq.conf.j2
    dest=/etc/dnsmasq.conf
    owner=root
    group=root
    mode=644
    backup=yes
  notify:
    - restart dnsmasq

- name: disable dnsmasq base in DHCP client
  lineinfile: >
    dest=/etc/dhcp/dhclient.conf
    line='prepend domain-name-servers 127.0.0.1;'
    owner=root
    group=root
    mode=0644
    backup=yes
  notify:
    - restart network manager
