---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family|lower }}.yml"
    - "default.yml"

- include: install_debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - samba

- include: configure.yml
  tags:
    - samba
