---
- name: get git bash prompt
  git:
    repo: "{{ account_git_bash_prompt_repo_url }}"
    dest: /opt/bash-git-prompt
    version: master
    depth: 1
    update: no

# create or update a user
- name: create users
  user:
    name: "{{ item.value.name }}"
    comment: "{{ item.value.comment | default(item.value.name) }}"
    shell: "{{ item.value.shell | default(omit) }}"
    system: "{{ item.value.system | default('no') }}"
    groups: "{{ item.value.groups | default(omit) | join(',') }}"
    append: "{{ item.value.append_groups | default('yes') }}"
    home: "{{ item.value.home|default(omit) }}"
    uid: "{{ item.value.uid|default(omit) }}"
    group: "{{ item.value.group|default(omit) }}"
  with_dict: "{{ account_users }}"

# add a ! at the beginning of hashed password to lock it
- name: set user password
  user:
    name: "{{ item.value.name }}"
    password: "{{ ('!' if item.value.lock|default(false) else '' ) ~ (account_user_passwords[item.value.name] |password_hash('sha512', item.value.salt|default(None))) }}"
  when: not item.value.no_password|default(false) and account_user_passwords[item.value.name] is defined
  with_dict: "{{ account_users }}"

- name: chmod homes
  file:
    path: "{{ (item.value.home|default('/home/' ~ item.value.name )) }}"
    mode: "{{ item.value.home_mode|default('u=rwx,g=rx,o=rx') }}"
    owner: "{{ item.value.home_owner|default(item.key) }}"
    group: "{{ item.value.home_group|default(item.key) }}"
    state: directory
  when: not item.value.no_chown_home|default(false)
  with_dict: "{{ account_users }}"

- name: copy home config files
  template:
    src: "{{ item.1.src }}"
    dest: "{{ item.0.home|default('/home/' ~ item.0.name) }}/{{ item.1.dest|default(item.1.src | basename | regex_replace('\\.j2', '') ) }}"
    owner: "{{ item.1.owner|default(item.0.name) }}"
    group: "{{ item.1.group|default(item.0.name) }}"
    mode: "{{ item.1.mode|default('u=rw,g=r,o=r') }}"
    backup: "{{ item.1.backup|default('yes') }}"
    force: "{{ item.1.force|default('no') }}"
  with_subelements:
    - "{{ account_users }}"
    - config_files
    - { skip_missing: True }
  when: item.1.src is not none

- name: set git configuration
  git_config:
    name: "{{ item.1.name }}"
    value: "{{ item.1.option }}"
    scope: global
  become: true
  become_user:  "{{ item.0.name }}"
  with_subelements:
    - "{{ account_users }}"
    - gitconfig
    - { skip_missing: True }
