---
- name: remove packages
  apt: name={{ item }} state=absent
  with_items: "{{ apt_remove_packages }}"

- name: install default packages
  apt: name={{ item }} state=present
  with_items: "{{ apt_default_packages }}"

- name: install extra packages
  apt: name={{ item }} state=present
  with_items: "{{ apt_extra_packages }}"
