---
- name: delete old SSH host keys
  file:
    path: "/etc/ssh/{{ item }}"
    state: absent
  when: ssh_server_regenerate_host_keys
  with_items:
    - ssh_host_rsa_key
    - ssh_host_rsa_key.pub
    - ssh_host_dsa_key
    - ssh_host_dsa_key.pub
    - ssh_host_ecdsa_key
    - ssh_host_ecdsa_key.pub
    - ssh_host_ed25519_key
    - ssh_host_ed25519_key.pub

- name: regenerate SSH host keys
  command: ssh-keygen -N "" -t {{ item.crypt }} -f /etc/ssh/{{ item.file }}
  when: ssh_server_regenerate_host_keys
  with_items:
    - { file: ssh_host_rsa_key, crypt: rsa }
    - { file: ssh_host_dsa_key, crypt: dsa }
    - { file: ssh_host_ecdsa_key, crypt: ecdsa }
    - { file: ssh_host_ed25519_key, crypt: ed25519 }
  notify: restart ssh server
