---
- name: install python 2
  yum: name={{ item }} state=present
  with_items:
      - python
      - python-devel
      - python-setuptools
      - python-virtualenv

- name: install python 3
  yum: name={{ item }} state=present
  when: python3_enabled
  with_items:
      - python34
      - python34-devel
      - python34-setuptools

- name: install pip for python 2
  easy_install: name=pip executable=easy_install-2.7

- name: install pip for python 3
  easy_install: name=pip executable=easy_install-3.4
  when: python3_enabled
