---
- name: install python 2
  apt: name={{ item }} state=present
  with_items:
      - python
      - python-dev
      - python-virtualenv
      - python-setuptools

- name: install python 3
  apt: name={{ item }} state=present
  when: python3_enabled
  with_items:
      - python3
      - python3-dev
      - python3-virtualenv
      - python3-setuptools

- name: install pip for python 2
  easy_install: name=pip executable=easy_install-2.7

- name: install pip for python 3
  easy_install: name=pip executable=easy_install3
  when: python3_enabled
